### ISSUE TITLE
Update 7.5 breaks everything

### ISSUE THREAD

**Issue by ZenithRogue** [Wetbikeboy2500/ScratchFixer#17]
I have no idea the cause, but the new buttons no-longer show

**Comment by ZenithRogue** [comment]
I just looked, and none of the features work at all now.

**Comment by Wetbikeboy2500** [comment]
I not seeing any of these issues. Weird.

**Comment by Wetbikeboy2500** [comment]
I just tested it on 3 different browsers. It seems to work with Chrome but not Firefox and Vivaldi.

**Comment by Wetbikeboy2500** [comment]
Update 7.6 should fix this. It was an issue with how the scopes for the let variables were global when in the if statement.

**Comment by ZenithRogue** [comment]
Weird. I was testing on a Chromebook, and I wasn't getting anything.
