### ISSUE TITLE
How To Remove?

### ISSUE THREAD

**Issue by radioblahaj** [Wetbikeboy2500/ScratchFixer#3]
Just Wondering. I Don't Have It Installted, Just Wonderig!

**Comment by Wetbikeboy2500** [comment]
What are you trying to remove? If it is the userscript, when you install it you can go to your userscript manager, like tampermonkey, and go to the dashboard and you can delete it from there.

**Comment by andybrwr** [comment]
If you have tampermonkey, click the icon then flip the on/off switch

**Comment by radioblahaj** [comment]
I Know. I DOn't have it, someone i know has it. Thnaks!

**Comment by andybrwr** [comment]
np, i guess??

**Comment by radioblahaj** [comment]
@ALinuxLover  Can you Help Me?

**Comment by andybrwr** [comment]
with what?

**Comment by radioblahaj** [comment]
Website!

**Comment by andybrwr** [comment]
what? youre making a website, you mean??

**Comment by radioblahaj** [comment]
Yeah WHy.

**Comment by radioblahaj** [comment]
Nah Iièm Kidding, I MAking A  high Tech Python Console And Some Cjrome Extestions.
Can you Please Help meÉ

**Comment by andybrwr** [comment]
confused

**Comment by radioblahaj** [comment]
Just Go To My COmmits

**Comment by andybrwr** [comment]
ok??
