### ISSUE TITLE
Add a button to download .sb2 files

### ISSUE THREAD

**Issue by infinitytec** [Wetbikeboy2500/ScratchFixer#30]
It would be nice if those of us without Flash could download projects and open them in the offline editor.

**Comment by Wetbikeboy2500** [comment]
I have worked on this for about 3 hours and have come to a conclusion. If you want something done right, then you have to do it yourself. Currently, there is no javascript sb2 downloader that actually works correctly, so I am going to have to make my own downloader. I'll try and get it done ASAP.
