### ISSUE TITLE
The 3.0 editor looks odd

### ISSUE THREAD

**Issue by infinitytec** [Wetbikeboy2500/ScratchFixer#40]
![image](https://user-images.githubusercontent.com/13670462/50619059-8a649980-0ebc-11e9-9cb0-365f631da7ac.png)
This may just be the dark theme.

**Comment by Wetbikeboy2500** [comment]
There are a lot of things that were messed up by this update. I am on it though.

**Comment by infinitytec** [comment]
It may be the MSU doing it.

Honestly, 3.0 feels like a beta still.

**Comment by Wetbikeboy2500** [comment]
It more of lacks customization and has input lag when going to the code menu even if you haven't placed a single block yet. I imagine this version will be modded a lot more to make up for these issues.
